### PR TITLE
makemake view doctors page UI skeleton

### PR DESCRIPTION
**Pull request by leroy-netizen**
I created the view doctor page skeleton. Still looking to add styling once I get a color pallete.

### CODE REVIEW

**Comment by MsMohamedHassan** [comment]
Gone through it, good work Leroy

**Review by MissZamzam — COMMENTED** [review]
Gone through, good work Leroy

**Review by loretta-dhahabu — APPROVED** [review]
good job Leroy

**Comment by MissZamzam** [comment]
merged and closed

**Pull request merged**
